### ISSUE TITLE
TypeError: set_bg_gradient_color() takes from 3 to 4 positional arguments but 7 were given

### ISSUE THREAD

**Issue by pweigel** [DanielWinklehner/py_electrodes#1]
pythonocc-core version: 0.18.2-dev

Error when running geo_example.py:
```
Traceback (most recent call last):
  File "geo_example.py", line 6, in <module>
    pe.show()
  File "/home/philip/venv/SimulationsVENV/lib/python3.6/site-packages/py_electrodes/py_electrodes.py", line 598, in show
    display, ais_shape = self._occ_obj.show(display, color=self._color)
  File "py_electrodes/py_electrodes_occ.pyx", line 450, in py_electrodes.py_electrodes_occ.PyOCCElectrode.show
TypeError: set_bg_gradient_color() takes from 3 to 4 positional arguments but 7 were given
```

This is coming from the format of the colors in set_bg_gradient_color(), it should be two lists rather than just six integers.
See: https://github.com/tpaviot/pythonocc-core/commit/b1bbf13e713305115281d36bd130e9816e865bdc

**Comment by DanielWinklehner** [comment]
Fixed in https://github.com/DanielWinklehner/py_electrodes/commit/50fca4da0773219f309f6ffc089500569293939d
