### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by pweigel** [DanielWinklehner/py_electrodes#2]
Getting an error when trying to import PyElectrode:
```
>>> from py_electrodes.py_electrodes import PyElectrode
/home/philip/.local/py_electrodes/Settings.txt
/home/philip/venv/SimulationsVENV/lib/python3.6/site-packages/py_electrodes/Settings.txt
Filepath2 exists
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philip/venv/SimulationsVENV/lib/python3.6/site-packages/py_electrodes/py_electrodes.py", line 21, in <module>
    OCC_GRADIENT1 = [int(item) for item in settings["OCC_GRADIENT1"].split("]")[0].split("[")[1].split(",")]
```

**Comment by pweigel** [comment]
This was an issue with having an old Settings.txt file.
